### ISSUE TITLE
Unhandled Exception: Connection refused

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/mosainfo-mobile-app#4]
## 오류 설명
에뮬레이터로 실행시 Flask 서버에 api 요청이 잘 보내지는 것을 확인했으나, 실제 아이폰에 연결하여 테스트해보니 다음과 같은 오류가 발생하며 Flask 서버에 api 요청이 보내지지 않는 것을 확인함.
```
2022-10-04 21:32:52.742757+0900 Runner[1002:688509] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Connection refused
#0      IOClient.send (package:http/src/io_client.dart:88:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:164:12)
<asynchronous suspension>
#3      HttpClient.getRequest (package:mosainfo_mobile_app/src/api/http_client.dart:22:16)
<asynchronous suspension>
#4      ProcessService.getProcessList (package:mosainfo_mobile_app/src/api/process_service.dart:10:33)
<asynchronous suspension>
#5      ProcessProvider.fetchProcessList (package:mosainfo_mobile_app/src/provider/process_provider.dart:13:20)
<asynchronous suspension>
```

**Comment by hanslelee** [comment]
## 오류 원인
Flask 서버에서 로컬호스트에서의 api 요청을 허용하고 있었기 때문에 발생한 오류임을 알 수 있었다. 따라서 로컬의 에뮬레이터에서 실행시 잘 작동되었던 것으로 보인다.

## 오류 해결
Flask 서버에서 외부 접속을 허용해주었다.
(백엔드 이슈 참고: https://github.com/Hi-DN/mosainfo-backend/issues/8)
